export default {
  GET_STARSHIP_DETAILS: "GET_STARSHIP_DETAILS",
  GET_STARSHIP_DETAILS_SUCCESS: "GET_STARSHIP_DETAILS_SUCCESS",
  GET_STARSHIP_DETAILS_ERROR: "GET_STARSHIP_DETAILS_ERROR",

  USER_SIGNUP_DETAILS_START: "USER_SIGNUP_DETAILS_START",
  USER_SIGNUP_DETAILS_SUCCESS: "USER_SIGNUP_DETAILS_SUCCESS",
  USER_SIGNUP_DETAILS_ERROR: "USER_SIGNUP_DETAILS_ERROR",

  PHARMACY_LOGIN_START: "PHARMACY_LOGIN_START",
  PHARMACY_LOGIN_SUCCESS: "PHARMACY_LOGIN_SUCCESS",
  PHARMACY_LOGIN_ERROR: "PHARMACY_LOGIN_ERROR",

  PHARMACY_SIGNUP_DETAILS_START: "PHARMACY_SIGNUP_DETAILS_START",
  PHARMACY_SIGNUP_DETAILS_SUCCESS: "PHARMACY_SIGNUP_DETAILS_SUCCESS",
  PHARMACY_SIGNUP_DETAILS_ERROR: "PHARMACY_SIGNUP_DETAILS_ERROR",

    RESEND_QR_DETAILS_START: "RESEND_QR_DETAILS_START",
    RESEND_QR_DETAILS_SUCCESS: "RESEND_QR_DETAILS_SUCCESS",
    RESEND_QR_DETAILS_ERROR: "RESEND_QR_DETAILS_ERROR",

  ROOT_CATEGORY_START:'ROOT_CATEGORY_START',
  ROOT_CATEGORY_SUCCESS:'ROOT_CATEGORY_SUCCESS',
  ROOT_CATEGORY_ERROR:'ROOT_CATEGORY_ERROR',
  
  PRODUCT_CATEGORY_START:'PRODUCT_CATEGORY_START',
  PRODUCT_CATEGORY_SUCCESS:'PRODUCT_CATEGORY_SUCCESS',
  PRODUCT_CATEGORY_ERROR:'PRODUCT_CATEGORY_ERROR',

  CREATE_PHARMACY_PRODUCT_START: "CREATE_PHARMACY_PRODUCT_START",
  CREATE_PHARMACY_PRODUCT_SUCCESS: "CREATE_PHARMACY_PRODUCT_SUCCESS",
  CREATE_PHARMACY_PRODUCT_ERROR: "CREATE_PHARMACY_PRODUCT_ERROR",

 UPLOAD_PRODUCT_IMAGE_START: "UPLOAD_PRODUCT_IMAGE_START",
 UPLOAD_PRODUCT_IMAGE_SUCCESS: "UPLOAD_PRODUCT_IMAGE_SUCCESS",
 UPLOAD_PRODUCT_IMAGE_ERROR: "UPLOAD_PRODUCT_IMAGE_ERROR",

  UPLOAD_VERIFICATION_DOCS_START: "UPLOAD_VERIFICATION_DOCS_START",
  UPLOAD_VERIFICATION_DOCS_SUCCESS: "UPLOAD_VERIFICATION_DOCS_SUCCESS",
  UPLOAD_VERIFICATION_DOCS_ERROR: "UPLOAD_VERIFICATION_DOCS_ERROR",

  VERIFY_OTP_START: "VERIFY_OTP_START",
  VERIFY_OTP_SUCCESS: "VERIFY_OTP_SUCCESS",
  VERIFY_OTP_ERROR: "VERIFY_OTP_ERROR",

  RESEND_VERIFY_OTP_START: "RESEND_VERIFY_OTP_START",
  RESEND_VERIFY_OTP_SUCCESS: "RESEND_VERIFY_OTP_SUCCESS",
  RESEND_VERIFY_OTP_ERROR: "RESEND_VERIFY_OTP_ERROR",

  FORGOT_PASSWORD_DETAILS_START: "FORGOT_PASSWORD_DETAILS_START",
  FORGOT_PASSWORD_DETAILS_SUCCESS: "FORGOT_PASSWORD_DETAILS_SUCCESS",
  FORGOT_PASSWORD_DETAILS_ERROR: "FORGOT_PASSWORD_DETAILS_ERROR",

  RESET_PASSWORD_DETAILS_START: "RESET_PASSWORD_DETAILS_START",
  RESET_PASSWORD_DETAILS_SUCCESS: "RESET_PASSWORD_DETAILS_SUCCESS",
  RESET_PASSWORD_DETAILS_ERROR: "RESET_PASSWORD_DETAILS_ERROR",

  UPDATE_PASSWORD_DETAILS_START: "UPDATE_PASSWORD_DETAILS_START",
  UPDATE_PASSWORD_DETAILS_SUCCESS: "UPDATE_PASSWORD_DETAILS_SUCCESS",
  UPDATE_PASSWORD_DETAILS_ERROR: "UPDATE_PASSWORD_DETAILS_ERROR",

  UPDATE_PROFILE_DETAILS_START: "UPDATE_PROFILE_DETAILS_START",
  UPDATE_PROFILE_DETAILS_SUCCESS: "UPDATE_PROFILE_DETAILS_SUCCESS",
  UPDATE_PROFILE_DETAILS_ERROR: "UPDATE_PROFILE_DETAILS_ERROR",

  EMAIL_VERIFICATION_DETAILS_START: "EMAIL_VERIFICATION_DETAILS_START",
  EMAIL_VERIFICATION_DETAILS_SUCCESS: "EMAIL_VERIFICATION_DETAILS_SUCCESS",
  EMAIL_VERIFICATION_DETAILS_ERROR: "EMAIL_VERIFICATION_DETAILS_ERROR",

 //GET PHARMACY PRODUCTS

    GET_PHARMACY_PRODUCTS_START: "GET_PHARMACY_PRODUCTS_START",
    GET_PHARMACY_PRODUCTS_SUCCESS: "GET_PHARMACY_PRODUCTS_SUCCESS",
    GET_PHARMACY_PRODUCTS_ERROR: "GET_PHARMACY_PRODUCTS_ERROR",

 // PHARMACY PRODUCT DETAIL

    GET_PHARMACY_PRODUCT_DETAIL_START: "GET_PHARMACY_PRODUCT_DETAIL_START",
    GET_PHARMACY_PRODUCT_DETAIL_SUCCESS: "GET_PHARMACY_PRODUCT_DETAIL_SUCCESS",
    GET_PHARMACY_PRODUCT_DETAIL_ERROR: "GET_PHARMACY_PRODUCT_DETAIL_ERROR",

    
//GET LANDING PAGE PRODUCTS
  GET_COVER_PRODUCTS_START:"GET_COVER_PRODUCTS_START",
  GET_COVER_PRODUCTS_SUCCESS:"GET_COVER_PRODUCTS_SUCCESS",
  GET_COVER_PRODUCTS_ERROR:"GET_COVER_PRODUCTS_ERROR",
 // ADD PHARMACY PRODUCT

    ADD_PHARMACY_PRODUCT_START: "ADD_PHARMACY_PRODUCT_START",
    ADD_PHARMACY_PRODUCT_SUCCESS: "ADD_PHARMACY_PRODUCT_SUCCESS",
    ADD_PHARMACY_PRODUCT_ERROR: "ADD_PHARMACY_PRODUCT_ERROR",

 // GET PRODUCT BY DIN NUMBER

    GET_PRODUCT_BY_DIN_START: "GET_PRODUCT_BY_DIN_START",
    GET_PRODUCT_BY_DIN_SUCCESS: "GET_PRODUCT_BY_DIN_SUCCESS",
    GET_PRODUCT_BY_DIN_ERROR: "GET_PRODUCT_BY_DIN_ERROR",

 // UPLOAD PHARMACY PRODUCT IMAGE

    UPLOAD_PHARMACY_PRODUCT_IMAGE_START: "UPLOAD_PHARMACY_PRODUCT_IMAGE_START",
    UPLOAD_PHARMACY_PRODUCT_IMAGE_SUCCESS: "UPLOAD_PHARMACY_PRODUCT_IMAGE_SUCCESS",
    UPLOAD_PHARMACY_PRODUCT_IMAGE_ERROR: "UPLOAD_PHARMACY_PRODUCT_IMAGE_ERROR",

    // REMOVE PHARMACY PRODUCT IMAGE

    REMOVE_PHARMACY_PRODUCT_IMAGE_START: "REMOVE_PHARMACY_PRODUCT_IMAGE_START",
    REMOVE_PHARMACY_PRODUCT_IMAGE_SUCCESS: "REMOVE_PHARMACY_PRODUCT_IMAGE_SUCCESS",
    REMOVE_PHARMACY_PRODUCT_IMAGE_ERROR: "REMOVE_PHARMACY_PRODUCT_IMAGE_ERROR",

};
